import { Raleway } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/header";

const RalewayFont = {
  subsets: ["latin"],
  weight: "400",
};

export const metadata = {
  title: "InsightVest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${RalewayFont.className}`}>
          <Header />
          <main className="min-h-screen">{children}</main>

          <footer className="bg-muted/50 py-12">
            <div className="container mx-auto px-4 text-center text-blue-400">
              <p>Made with 💗 by RoadsideCoder</p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
